name: dhobighat-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - motor==3.3.1
    - pymongo==4.6.0
    - pydantic==2.5.0
    - python-multipart==0.0.6
    - python-dotenv==1.0.0 
    - httpx==0.25.2
    - aiohttp==3.9.0
    - requests==2.31.0